# Generated by Django 3.2 on 2021-05-03 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('place_code', models.TextField(unique=True, verbose_name='Código de aparcamiento')),
            ],
            options={
                'verbose_name': 'Aparcamiento',
                'verbose_name_plural': 'Lista de aparcamientos',
            },
        ),
        migrations.CreateModel(
            name='PasswordRecovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('expiration_date', models.DateTimeField(verbose_name='Fecha de vencimiento')),
                ('is_used', models.BooleanField(default=False, verbose_name='Fue usado')),
                ('token', models.TextField(verbose_name='Token')),
            ],
            options={
                'verbose_name': 'Recuperación de contraseña',
                'verbose_name_plural': 'Recuperación de contraseña',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('price', models.IntegerField(default=0, verbose_name='Valor')),
                ('concept', models.TextField(default='', verbose_name='concepto')),
                ('status', models.CharField(choices=[('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('pending', 'Pendiente'), ('failed', 'Fallida'), ('abandoned', 'Abandonada'), ('cancelled', 'Cancelado')], default='pending', max_length=25, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('initial_hour', models.DateTimeField(verbose_name='Hora de inicio')),
                ('final_hour', models.DateTimeField(blank=True, null=True, verbose_name='Hora de finalización')),
                ('vehicle_plate', models.TextField(verbose_name='Placa de vehículo')),
                ('vehicle_type', models.TextField(choices=[('auto', 'Automovil'), ('moto', 'Motocicleta')], default='auto', verbose_name='Tipo de vehículo')),
                ('document_number', models.TextField(blank=True, null=True, verbose_name='Número de documento')),
                ('email', models.TextField(blank=True, null=True, verbose_name='Correo electrónico')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='Cancelado')),
                ('slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot', to='api.parkingslot')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservaciones',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='vehicle_type',
            field=models.TextField(choices=[('auto', 'Automovil'), ('moto', 'Motocicleta')], default='auto', verbose_name='Tipo de vehículo'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile',
        ),
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.CharField(choices=[('user', 'Cliente'), ('admin', 'Administrador')], default='user', max_length=255, verbose_name='Perfil'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.reservation'),
        ),
        migrations.AddField(
            model_name='passwordrecovery',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PR_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
