# Generated by Django 3.2 on 2021-05-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210513_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingslot',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='está activo'),
        ),
    ]
